module.exports = {
    mode: "jit",
    content: [
        "./components/**/*.{js,vue,ts}",
        "./layouts/**/*.vue",
        "./pages/**/*.vue",
        "./plugins/**/*.{js,ts}",
        "./nuxt.config.{js,ts}",
    ],
    theme: {
        extend: {
            colors: {
                primary: "#395D64",
                gray: "#606060",
                "gray-two": "#9C9C9C",
                "gray-three": "#686868",
                "gray-400": "#5A5A5A",
                "gray-500": "#7E7E7E",
                "gray-600": "#9E9E9E",
                "gray-700": "#706F6F",
                "gray-800": "#EDEDED",
                "gray-900": "#8D8D8D",
                "gray-1000": "#DAD9D7",
                "gray-1100": "#7B7B7B",
                "gray-1200": "#A8A8A8",
                green: "#243D42",
                "green-two": "#377885",
                lightblue: "#3D626B",
                blue: "#7CB7C2",
                "blue-200": "#AAB9BC",
                "lightblue-200": "#E4F1F4",
                "cyan-light": "#DBEDF0",
                cream: "#F2EBE3",
                white: "#FFFFFF",
                linen: "#FCEBE5",
                pink: "#F4CFC1",
                brown: "#BF5B35",
                cultured: "#F5F7F7",
                verdigris: "#49A4B4",
                onyx: "#383838",
                olive: "#3E3E3E",
                silver: "#B2B2B2",
            },
            fontFamily: {
                roboto: ["Roboto"],
                workSans: ["Work-Sans"],
            },
        },
        screens: {
            xms: "20em",
            msm: "23.5em",
            sm: "25.5em",
            "m-sm": { max: "25.5em" },
            md: "48em",
            "m-md": { max: "48em" },
            mobile: { max: "767px" },
            tabletver: { max: "1024px" },
            lg: "62em",
            "m-lg": { max: "62em" },
            xl: "72em",
            "m-xl": { max: "71.5em" },
            tablet: { max: "1024px" },
            xlg: "75em",
            "m-xlg": { max: "75em" },
            laptop: { max: "1600px" },
            design: "89em",
            xxlg: "96em",
            monitor: "106em",
        },
    },
    plugins: [],
};